Repository HuCaresTeam/schedulearn, pull requests merged in 2020-05, with the labels that each got.

#14 Added linting to frontend CI
  .github/workflows/frontend.yml
  schedulearn-frontend/src/components/WorkerList.tsx
  schedulearn-frontend/src/components/WorkerListExample.tsx
Labels: enhancement

#13 Linked up calendar to backend.
  SchedulearnBackend/SchedulearnBackend/BaseVMs/LearningDayVM.cs
  SchedulearnBackend/SchedulearnBackend/Startup.cs
  schedulearn-frontend/src/components/Calendar/EventAddForm.scss
  schedulearn-frontend/src/components/Calendar/EventAddForm.tsx
  schedulearn-frontend/src/components/Calendar/LearningDayEvent.ts
  schedulearn-frontend/src/components/LearningDayCalendar.tsx
  schedulearn-frontend/src/components/NestedList/NestedList.scss
  schedulearn-frontend/src/components/NestedList/NestedList.tsx
  schedulearn-frontend/src/index.tsx
  schedulearn-frontend/src/server-components/LearningDayCalendarProvider.tsx
  schedulearn-frontend/src/server-components/UserLearningDayCalendar.tsx
Labels: enhancement

#12 Worker list backend
  SchedulearnBackend/SchedulearnBackend/BaseVMs/AnalyzeDataVM.cs
  schedulearn-frontend/src/components/WorkerList/WorkerList.css
  schedulearn-frontend/src/components/WorkerList/WorkerList.tsx
  schedulearn-frontend/src/components/WorkerListExample.tsx
  schedulearn-frontend/src/index.tsx
  schedulearn-frontend/src/server-components/AnalyzeData.tsx
  schedulearn-frontend/src/server-components/WorkerListByTopic.tsx
Labels: enhancement

#10 Feat/reac routing
  .gitignore
  schedulearn-frontend/package-lock.json
  schedulearn-frontend/package.json
  schedulearn-frontend/src/components/Contexts/UserContext.tsx
  schedulearn-frontend/src/components/Login/LoginPage.tsx
  schedulearn-frontend/src/index.tsx
Labels: enhancement

#15 feat/all-user-learning-calendar
  SchedulearnBackend/SchedulearnBackend/BaseVMs/LearningDayVM.cs
  SchedulearnBackend/SchedulearnBackend/BaseVMs/UserBaseVM.cs
  schedulearn-frontend/.eslintrc.js
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/components/Calendar/EventAddForm.tsx
  schedulearn-frontend/src/components/Calendar/EventAddModal.tsx
  schedulearn-frontend/src/components/Calendar/LearningDayCalendar.tsx
  schedulearn-frontend/src/components/Calendar/LearningDayEvent.ts
  schedulearn-frontend/src/components/Calendar/WeekViewCalendar.tsx
  schedulearn-frontend/src/components/Contexts/UserContext.tsx
  schedulearn-frontend/src/components/LearningDayCalendar.tsx
  schedulearn-frontend/src/components/Login/LoginPage.tsx
  schedulearn-frontend/src/components/NestedList/NestedList.tsx
  schedulearn-frontend/src/index.tsx
  schedulearn-frontend/src/server-components/AllUserLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/LearningDayCalendarProvider.tsx
  schedulearn-frontend/src/server-components/Login/LoginPage.tsx
  schedulearn-frontend/src/server-components/TopicList.tsx
  schedulearn-frontend/src/server-components/UserLearningDayCalendar.tsx
  schedulearn-frontend/src/util-types/AtLeast.ts
Labels: enhancement

#17 Added whitespace and newline linting
  schedulearn-frontend/.eslintrc.js
  schedulearn-frontend/src/server-components/AnalyzeData.tsx
  schedulearn-frontend/src/server-components/WorkerListByTopic.tsx
Labels: hotfix

#18 Started moving Dotnetify UserVM functionality to API controller
  SchedulearnBackend/SchedulearnBackend/BaseVMs/TopicList.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/User/CreateNewUser.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/User/LimitsToApply.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/UserController.cs
  SchedulearnBackend/SchedulearnBackend/Middleware/ErrorHandlingMeddleware.cs
  SchedulearnBackend/SchedulearnBackend/Models/JobTitle.cs
  SchedulearnBackend/SchedulearnBackend/Models/Limit.cs
  SchedulearnBackend/SchedulearnBackend/Models/Team.cs
  SchedulearnBackend/SchedulearnBackend/Models/Topic.cs
  SchedulearnBackend/SchedulearnBackend/Models/User.cs
  SchedulearnBackend/SchedulearnBackend/Services/LimitService.cs
  SchedulearnBackend/SchedulearnBackend/Services/TeamService.cs
  SchedulearnBackend/SchedulearnBackend/Services/UserService.cs
  SchedulearnBackend/SchedulearnBackend/Startup.cs
  SchedulearnBackend/SchedulearnBackend/UserFriendlyExceptions/NotFoundException.cs
  SchedulearnBackend/SchedulearnBackend/UserFriendlyExceptions/UserFriendlyException.cs
Labels: enhancement

#20 Added Team controller and service
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/LimitsToApply.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/Team/CreateNewTeam.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/Team/TeamTransfer.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/TeamController.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/UserController.cs
  SchedulearnBackend/SchedulearnBackend/Services/TeamService.cs
  SchedulearnBackend/SchedulearnBackend/Services/UserService.cs
Labels: enhancement

#19 Topic list implementation ported to API
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/Topic/CreateNewTopic.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/Topic/ModifiedTopic.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/TopicController.cs
  SchedulearnBackend/SchedulearnBackend/Models/Topic.cs
  SchedulearnBackend/SchedulearnBackend/Services/TopicService.cs
  SchedulearnBackend/SchedulearnBackend/Startup.cs
Labels: enhancement

#21 LearningDayVM functionality ported to API
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/LearningDay/CreateNewLearningDay.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/LearningDay/FlatLearningDay.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/LearninDayController.cs
  SchedulearnBackend/SchedulearnBackend/Services/LearningDayService.cs
  SchedulearnBackend/SchedulearnBackend/Startup.cs
Labels: enhancement

#22 Added AnalyzeData controller and service
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/LearningDay/LearningDayWithUser.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/LearninDayController.cs
  SchedulearnBackend/SchedulearnBackend/Services/LearningDayService.cs
  SchedulearnBackend/SchedulearnBackend/Startup.cs
Labels: enhancement

#23 Added Jwt token authorization
  SchedulearnBackend/SchedulearnBackend/Controllers/JobTitleController.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/TeamController.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/TopicController.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/UserController.cs
  SchedulearnBackend/SchedulearnBackend/Models/AuthenticateModel.cs
  SchedulearnBackend/SchedulearnBackend/SchedulearnBackend.csproj
  SchedulearnBackend/SchedulearnBackend/Services/UserService.cs
  SchedulearnBackend/SchedulearnBackend/Startup.cs
  SchedulearnBackend/SchedulearnBackend/UserFriendlyExceptions/UnauthorizedException.cs
  SchedulearnBackend/SchedulearnBackend/appsettings.json
Labels: enhancement

#25 Feat/move frontend to api
  SchedulearnBackend/SchedulearnBackend/Controllers/LearninDayController.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/UserController.cs
  schedulearn-frontend/package-lock.json
  schedulearn-frontend/package.json
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/Constants.ts
  schedulearn-frontend/src/HttpStatusCode.ts
  schedulearn-frontend/src/PrivateRoute.tsx
  schedulearn-frontend/src/UserContext.tsx
  schedulearn-frontend/src/api-contract/FlatLearningDay.ts
  schedulearn-frontend/src/api-contract/Topic.ts
  schedulearn-frontend/src/api-contract/User.ts
  schedulearn-frontend/src/components/Calendar/EventAddForm.tsx
  schedulearn-frontend/src/components/Calendar/EventAddModal.tsx
  schedulearn-frontend/src/components/Calendar/LearningDayCalendar.tsx
  schedulearn-frontend/src/components/NestedList/NestedList.tsx
  schedulearn-frontend/src/components/NestedList/NestedListItem.tsx
  schedulearn-frontend/src/server-components/AllUserLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/AnalyzeData.tsx
  schedulearn-frontend/src/server-components/LearningDayCalendarProvider.tsx
  schedulearn-frontend/src/server-components/Login/LoginPage.tsx
  schedulearn-frontend/src/server-components/TopicList.tsx
  schedulearn-frontend/src/server-components/TopicListProvider.tsx
  schedulearn-frontend/src/server-components/UserLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/WorkerListByTopic.tsx
Labels: enhancement

#24 Pjuvis topics by team
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/Team/TeamMembers.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/Topic/TeamTopics.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/Topic/TopicNoSubtopics.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/User/SimpleUser.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/TeamController.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/TopicController.cs
  SchedulearnBackend/SchedulearnBackend/Models/User.cs
  SchedulearnBackend/SchedulearnBackend/Services/LearningDayService.cs
  SchedulearnBackend/SchedulearnBackend/Services/TeamService.cs
  SchedulearnBackend/SchedulearnBackend/Services/TopicService.cs
Labels: enhancement

#26 Added description modification capability to calendar.
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/LearningDay/ModifyLearningDay.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/LearninDayController.cs
  SchedulearnBackend/SchedulearnBackend/Services/LearningDayService.cs
  schedulearn-frontend/src/components/Calendar/EventAddModal.tsx
  schedulearn-frontend/src/components/Calendar/EventForm.scss
  schedulearn-frontend/src/components/Calendar/EventForm.tsx
  schedulearn-frontend/src/components/Calendar/EventModal.scss
  schedulearn-frontend/src/components/Calendar/EventModal.tsx
  schedulearn-frontend/src/components/Calendar/LearningDayCalendar.tsx
  schedulearn-frontend/src/components/NestedList/NestedList.tsx
  schedulearn-frontend/src/server-components/AllUserLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/TopicList.tsx
  schedulearn-frontend/src/server-components/UserLearningDayCalendar.tsx
Labels: enhancement

#30 Nested List supports max height property
  schedulearn-frontend/src/components/Calendar/EventForm.tsx
  schedulearn-frontend/src/components/NestedList/NestedList.tsx
  schedulearn-frontend/src/server-components/TopicList.tsx
Labels: enhancement

#33 Added support for My Limits view in fornt-end and back-end
  SchedulearnBackend/SchedulearnBackend/Controllers/LimitController.cs
  SchedulearnBackend/SchedulearnBackend/Services/LimitService.cs
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/components/LearningLimits/LearningLimits.tsx
  schedulearn-frontend/src/server-components/LimitViewer.tsx
Labels: enhancement

#31 GetAccessibleTeams logic change and added ManagedTeamsSelect
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/Team/FlatTeam.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/TeamController.cs
  SchedulearnBackend/SchedulearnBackend/Services/TeamService.cs
  SchedulearnBackend/SchedulearnBackend/Services/TopicService.cs
  schedulearn-frontend/src/components/TeamsList/TeamList.tsx
  schedulearn-frontend/src/components/TeamsList/TeamListSelectItem.tsx
  schedulearn-frontend/src/server-components/ManagedTeamsSelect.tsx
Labels: enhancement

#34 Feat/new topic creation
  schedulearn-frontend/src/components/NestedList/NestedList.scss
  schedulearn-frontend/src/components/NestedList/NestedList.tsx
  schedulearn-frontend/src/components/NestedList/TopicAddForm.scss
  schedulearn-frontend/src/components/NestedList/TopicAddForm.tsx
  schedulearn-frontend/src/components/NestedList/TopicAddModal.scss
  schedulearn-frontend/src/components/NestedList/TopicAddModal.tsx
  schedulearn-frontend/src/server-components/TopicList.tsx
Labels: enhancement

#32 Moved learning day to API. Removed dotnetify.
  SchedulearnBackend/SchedulearnBackend/BaseVMs/AnalyzeDataVM.cs
  SchedulearnBackend/SchedulearnBackend/BaseVMs/HelloWorld.cs
  SchedulearnBackend/SchedulearnBackend/BaseVMs/LearningDayVM.cs
  SchedulearnBackend/SchedulearnBackend/BaseVMs/TeamVM.cs
  SchedulearnBackend/SchedulearnBackend/BaseVMs/TopicList.cs
  SchedulearnBackend/SchedulearnBackend/BaseVMs/UserBaseVM.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/LearningDay/LearningDayWithUser.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/LearninDayController.cs
  SchedulearnBackend/SchedulearnBackend/Models/Team.cs
  SchedulearnBackend/SchedulearnBackend/Models/Topic.cs
  SchedulearnBackend/SchedulearnBackend/Models/User.cs
  SchedulearnBackend/SchedulearnBackend/Program.cs
  SchedulearnBackend/SchedulearnBackend/SchedulearnBackend.csproj
  SchedulearnBackend/SchedulearnBackend/Startup.cs
  schedulearn-frontend/package-lock.json
  schedulearn-frontend/package.json
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/api-contract/CreateNewLearningDay.ts
  schedulearn-frontend/src/api-contract/FlatLearningDay.ts
  schedulearn-frontend/src/api-contract/LearningDayWithUser.ts
  schedulearn-frontend/src/components/WorkerList/WorkerList.tsx
  schedulearn-frontend/src/server-components/AllUserLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/HelloWorld.tsx
  schedulearn-frontend/src/server-components/LearningDaysByTopic.tsx
  schedulearn-frontend/src/server-components/UserLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/UserLearningDaysByTopicView.tsx
  schedulearn-frontend/src/server-components/WorkerListByTopic.tsx
Labels: enhancement

#35 Added TopicsByManagerView
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/components/FlatTopicList/FlatTopicList.scss
  schedulearn-frontend/src/components/FlatTopicList/FlatTopicList.tsx
  schedulearn-frontend/src/server-components/Views/TopicsByManagerView.tsx
Labels: enhancement

#36 Changed info modal z-index to be on top of event modal.
  SchedulearnBackend/SchedulearnBackend/Services/LearningDayService.cs
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/components/Calendar/EventForm.scss
  schedulearn-frontend/src/components/Calendar/EventForm.tsx
  schedulearn-frontend/src/components/NestedList/ItemInfoModal.tsx
  schedulearn-frontend/src/components/NestedList/TopicAddForm.tsx
  schedulearn-frontend/src/server-components/Views/UserLearningDaysByTopicView.tsx
Labels: hotfix

#37 Added team learning day calendar.
  SchedulearnBackend/SchedulearnBackend/Controllers/LearninDayController.cs
  SchedulearnBackend/SchedulearnBackend/Extensions/StringExtensions.cs
  SchedulearnBackend/SchedulearnBackend/Properties/Resources.Designer.cs
  SchedulearnBackend/SchedulearnBackend/Properties/Resources.resx
  SchedulearnBackend/SchedulearnBackend/SchedulearnBackend.csproj
  SchedulearnBackend/SchedulearnBackend/Services/LearningDayService.cs
  schedulearn-frontend/package-lock.json
  schedulearn-frontend/package.json
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/ColorTest.tsx
  schedulearn-frontend/src/Constants.ts
  schedulearn-frontend/src/components/Calendar/EventForm.tsx
  schedulearn-frontend/src/components/Calendar/LearningDayCalendar.tsx
  schedulearn-frontend/src/components/Calendar/WeekViewCalendar.tsx
  schedulearn-frontend/src/server-components/AllUserLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/TeamLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/UserLearningDayCalendar.tsx
  schedulearn-frontend/src/utils/AtLeast.ts
  schedulearn-frontend/src/utils/ColorMapper.ts
Labels: enhancement

#42 Style for navigation menu
  schedulearn-frontend/src/App.scss
  schedulearn-frontend/src/App.tsx
Labels: enhancement

#38 Disabled list item
  schedulearn-frontend/src/components/NestedList/NestedList.scss
  schedulearn-frontend/src/components/NestedList/NestedList.tsx
  schedulearn-frontend/src/components/NestedList/NestedListItem.scss
  schedulearn-frontend/src/components/NestedList/NestedListItem.tsx
  schedulearn-frontend/src/index.scss
Labels: enhancement

#41 Added filtering for specific user in teams calendar
  schedulearn-frontend/src/api-contract/Team.ts
  schedulearn-frontend/src/components/Calendar/UserList/UserList.tsx
  schedulearn-frontend/src/components/Calendar/UserList/UserListSelectItem.tsx
  schedulearn-frontend/src/server-components/TeamLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/UsersInTeamList.tsx
Labels: enhancement

#46 Fixed modal x and y
  schedulearn-frontend/src/components/NestedList/NestedList.tsx
Labels: hotfix

#45 Feat/suggested topics
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/api-contract/SuggestionForUser.ts
  schedulearn-frontend/src/components/Suggestions/SuggestionsList.tsx
  schedulearn-frontend/src/server-components/Suggestions.tsx
Labels: enhancement

#47 Create user
  SchedulearnBackend/SchedulearnBackend/Controllers/UserController.cs
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/components/ManagedTeam/CreateUser.tsx
  schedulearn-frontend/src/server-components/CreateUserForm.tsx
Labels: enhancement

#48 Feat/login rewrite
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/User/UserWithoutPassword.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/UserController.cs
  SchedulearnBackend/SchedulearnBackend/Services/UserService.cs
  schedulearn-frontend/package-lock.json
  schedulearn-frontend/package.json
  schedulearn-frontend/src/App.scss
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/PrivateRoute.tsx
  schedulearn-frontend/src/UserContext.tsx
  schedulearn-frontend/src/api-services/History.ts
  schedulearn-frontend/src/api-services/UserContext.tsx
  schedulearn-frontend/src/api-services/api-contract/CreateNewLearningDay.ts
  schedulearn-frontend/src/api-services/api-contract/LearningDayWithUser.ts
  schedulearn-frontend/src/api-services/api-contract/SimpleUser.ts
  schedulearn-frontend/src/api-services/api-contract/SuggestionForUser.ts
  schedulearn-frontend/src/api-services/api-contract/Team.ts
  schedulearn-frontend/src/api-services/api-contract/TeamByTopic.ts
  schedulearn-frontend/src/api-services/api-contract/Topic.ts
  schedulearn-frontend/src/api-services/api-contract/User.ts
  schedulearn-frontend/src/components/Calendar/UserList/UserList.tsx
  schedulearn-frontend/src/components/Calendar/UserList/UserListSelectItem.tsx
  schedulearn-frontend/src/components/Contexts/UserContext.tsx
  schedulearn-frontend/src/components/Suggestions/SuggestionsList.tsx
  schedulearn-frontend/src/navigation-components/AppNav.scss
  schedulearn-frontend/src/navigation-components/AppNav.tsx
  schedulearn-frontend/src/navigation-components/NavItem.tsx
  schedulearn-frontend/src/server-components/CreateUserForm.tsx
  schedulearn-frontend/src/server-components/LearningDaysByTopic.tsx
  schedulearn-frontend/src/server-components/LimitViewer.tsx
  schedulearn-frontend/src/server-components/Login/LoginPage.tsx
  schedulearn-frontend/src/server-components/ManagedTeamsSelect.tsx
  schedulearn-frontend/src/server-components/Suggestions.tsx
  schedulearn-frontend/src/server-components/TeamLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/TeamsByTopicList/TeamsByTopicList.tsx
  schedulearn-frontend/src/server-components/TopicList.tsx
  schedulearn-frontend/src/server-components/UserLearningDayCalendar.tsx
  schedulearn-frontend/src/server-components/UsersInTeamList.tsx
  schedulearn-frontend/src/server-components/Views/TeamsByTopicView.tsx
  schedulearn-frontend/src/server-components/Views/TopicsByManagerView.tsx
Labels: enhancement

#49 View Members by topic now shows only managers team members
  SchedulearnBackend/SchedulearnBackend/Controllers/LearninDayController.cs
  SchedulearnBackend/SchedulearnBackend/Services/LearningDayService.cs
  schedulearn-frontend/src/server-components/LearningDaysByTopic.tsx
Labels: hotfix

#50 Added month view to calendar. Enabled popup
  schedulearn-frontend/src/components/Calendar/WeekViewCalendar.scss
  schedulearn-frontend/src/components/Calendar/WeekViewCalendar.tsx
Labels: enhancement

#52 Feat/page wide errors
  SchedulearnBackend/SchedulearnBackend/Controllers/LearninDayController.cs
  SchedulearnBackend/SchedulearnBackend/Middleware/ErrorHandlingMeddleware.cs
  SchedulearnBackend/SchedulearnBackend/Properties/launchSettings.json
  schedulearn-frontend/src/App.scss
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/api-services/UserContext.tsx
  schedulearn-frontend/src/components/Calendar/EventModal.tsx
  schedulearn-frontend/src/components/Calendar/LearningDayCalendar.tsx
  schedulearn-frontend/src/components/Calendar/UserList/UserList.tsx
  schedulearn-frontend/src/components/Calendar/WeekViewCalendar.scss
  schedulearn-frontend/src/components/NestedList/ItemInfoModal.tsx
  schedulearn-frontend/src/components/NestedList/TopicAddModal.tsx
  schedulearn-frontend/src/index.scss
  schedulearn-frontend/src/navigation-components/AppError.scss
  schedulearn-frontend/src/navigation-components/AppError.tsx
Labels: enhancement

#53 Added managers managed users endpoint
  SchedulearnBackend/SchedulearnBackend/Controllers/UserController.cs
  SchedulearnBackend/SchedulearnBackend/Services/UserService.cs
Labels: enhancement

#56 Feat/learning tree
  schedulearn-frontend/package-lock.json
  schedulearn-frontend/package.json
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/components/TopicTree/TopicTree.scss
  schedulearn-frontend/src/components/TopicTree/TopicTree.tsx
  schedulearn-frontend/src/index.tsx
  schedulearn-frontend/src/navigation-components/AppNav.tsx
  schedulearn-frontend/src/server-components/UserTopicTree.tsx
  schedulearn-frontend/types/react-tree-graph/index.d.ts
Labels: enhancement

#58 Changed to transient. Fixed bug with registration form
  SchedulearnBackend/SchedulearnBackend/Startup.cs
  schedulearn-frontend/src/components/Registration/RegistrationForm.tsx
Labels: enhancement

#59 Fixed bug with NoContent json
  schedulearn-frontend/src/api-services/UserContext.tsx
Labels: hotfix

#54 Feat/manager suggestions
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/Suggestion/CreateNewSuggestion.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/SuggestionController.cs
  SchedulearnBackend/SchedulearnBackend/Services/SuggestionService.cs
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/api-services/api-contract/CreateNewSuggestion.ts
  schedulearn-frontend/src/components/Suggestions/CreateSuggestion.tsx
  schedulearn-frontend/src/components/Suggestions/SuggestionForm.scss
  schedulearn-frontend/src/components/Suggestions/SuggestionForm.tsx
  schedulearn-frontend/src/navigation-components/AppNav.tsx
  schedulearn-frontend/src/pages/SuggestionsPage.tsx
  schedulearn-frontend/src/server-components/Suggestion/NewSuggestions.tsx
  schedulearn-frontend/src/server-components/Suggestion/Suggestions.tsx
Labels: enhancement

#61 Added optimization for getting accessible teams.
  SchedulearnBackend/SchedulearnBackend/Controllers/TeamController.cs
  SchedulearnBackend/SchedulearnBackend/SchedulearnBackend.csproj
  SchedulearnBackend/SchedulearnBackend/Services/TeamService.cs
  SchedulearnBackend/SchedulearnBackend/Services/TopicService.cs
  SchedulearnBackend/SchedulearnBackend/Services/UserService.cs
  schedulearn-frontend/src/api-services/UserContext.tsx
  schedulearn-frontend/src/components/FlatTopicList/FlatTopicList.tsx
  schedulearn-frontend/src/server-components/Views/UserLearningDaysByTopicView.tsx
Labels: bug, enhancement

#65 Feat/registration bootstrap
  schedulearn-frontend/src/components/NestedList/info.svg
  schedulearn-frontend/src/components/Registration/RegistrationForm.tsx
Labels: enhancement

#70 Added limits tracking logic
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/LearningDay/CreateNewLearningDay.cs
  SchedulearnBackend/SchedulearnBackend/Properties/Resources.Designer.cs
  SchedulearnBackend/SchedulearnBackend/Properties/Resources.resx
  SchedulearnBackend/SchedulearnBackend/Services/LearningDayService.cs
  SchedulearnBackend/SchedulearnBackend/UserFriendlyExceptions/LimitUsed.cs
  schedulearn-frontend/src/server-components/UserLearningDayCalendar.tsx
Labels: enhancement

#71 Calendar typo
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/navigation-components/AppNav.tsx
  schedulearn-frontend/src/pages/TeamCalendarPage.tsx
Labels: enhancement

#72 Renamed views
  schedulearn-frontend/src/App.tsx
  schedulearn-frontend/src/navigation-components/AppNav.tsx
  schedulearn-frontend/src/server-components/Views/UserLearningDaysByTopicView.tsx
Labels: enhancement

#74 Added transaction for every request
  SchedulearnBackend/SchedulearnBackend/Middleware/TransactionFilter.cs
  SchedulearnBackend/SchedulearnBackend/Startup.cs
Labels: enhancement

#77 Fixed migration transaction
  SchedulearnBackend/SchedulearnBackend/Startup.cs
Labels: bug, enhancement

#76 Add creating new job title functionality
  SchedulearnBackend/SchedulearnBackend/Controllers/DTOs/NewJobTitle/CreateJobTitle.cs
  SchedulearnBackend/SchedulearnBackend/Controllers/JobTitleController.cs
  schedulearn-frontend/src/components/ManagedTeam/CreateUser.tsx
Labels: enhancement
